'use client';
import { useEffect,useRef,useState } from 'react';
type Img={id:string;display_blob_key:string;thumbnail_blob_key:string};
export default function MotorcycleGallery({images,title}:{images:Img[];title:string}){
  const [i,setI]=useState(0);const [open,setOpen]=useState(false);const opener=useRef<HTMLButtonElement>(null);const closeRef=useRef<HTMLButtonElement>(null);const touchX=useRef<number|null>(null);
  const prev=()=>setI(v=>(v-1+images.length)%images.length);const next=()=>setI(v=>(v+1)%images.length);
  useEffect(()=>{if(!open)return;closeRef.current?.focus();const f=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowLeft')prev();if(e.key==='ArrowRight')next()};document.body.style.overflow='hidden';window.addEventListener('keydown',f);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',f);setTimeout(()=>opener.current?.focus(),0)}},[open,images.length]);
  if(!images.length)return null;
  const swipeStart=(e:React.TouchEvent)=>{touchX.current=e.touches[0]?.clientX??null};
  const swipeEnd=(e:React.TouchEvent)=>{if(touchX.current===null)return;const end=e.changedTouches[0]?.clientX??touchX.current;const delta=end-touchX.current;touchX.current=null;if(Math.abs(delta)>50)(delta<0?next:prev)()};
  return <div className="gallery"><div className="gallery-main"><button ref={opener} onClick={()=>setOpen(true)} style={{border:0,padding:0,width:'100%',height:'100%',background:'transparent'}} aria-label="Άνοιγμα φωτογραφίας σε πλήρη οθόνη"><img src={`/media/${encodeURIComponent(images[i].display_blob_key)}`} alt={`${title} - φωτογραφία ${i+1}`}/></button>{images.length>1&&<><button className="gallery-arrow prev" onClick={prev} aria-label="Προηγούμενη φωτογραφία">‹</button><button className="gallery-arrow next" onClick={next} aria-label="Επόμενη φωτογραφία">›</button></>}</div><div className="thumbs">{images.map((im,n)=><button key={im.id} className={`thumb ${n===i?'active':''}`} onClick={()=>setI(n)} aria-label={`Φωτογραφία ${n+1}`}><img src={`/media/${encodeURIComponent(im.thumbnail_blob_key)}`} alt=""/></button>)}</div>{open&&<div className="fullscreen" role="dialog" aria-modal="true" aria-label="Προβολή φωτογραφίας" onTouchStart={swipeStart} onTouchEnd={swipeEnd} onClick={e=>{if(e.currentTarget===e.target)setOpen(false)}}><img src={`/media/${encodeURIComponent(images[i].display_blob_key)}`} alt={`${title} - φωτογραφία ${i+1}`}/><button ref={closeRef} className="close" onClick={()=>setOpen(false)} aria-label="Κλείσιμο προβολής">×</button>{images.length>1&&<><button className="gallery-arrow prev" onClick={prev} aria-label="Προηγούμενη φωτογραφία">‹</button><button className="gallery-arrow next" onClick={next} aria-label="Επόμενη φωτογραφία">›</button></>}</div>}</div>
}
