import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import MotorcycleGallery from '@/components/public/MotorcycleGallery';
import { getImages,getPublicListingBySlug } from '@/lib/db/listings';
import { formatCc,formatKm,formatPrice } from '@/lib/formatting';
import { siteConfig } from '@/lib/config/site';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const l=await getPublicListingBySlug(slug);if(!l)return {};const images=await getImages(l.id);const cover=(images.find(x=>x.is_cover)??images[0])?.display_blob_key;return {title:`${l.title} προς πώληση`,description:`${l.title}, ${formatPrice(l.price_eur)}, ${l.registration_year}, ${formatKm(l.kilometers)}, ${formatCc(l.engine_cc)}. ${l.description.slice(0,120)}`,alternates:{canonical:`/aggelies/${l.slug}`},openGraph:{title:`${l.title} | Moto Prionas`,description:l.description.slice(0,160),images:cover?[`/media/${encodeURIComponent(cover)}`]:[]}}}
export default async function ListingPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const l=await getPublicListingBySlug(slug);if(!l)notFound();const images=await getImages(l.id);const schema={"@context":"https://schema.org","@type":"Product",name:l.title,image:images.map(i=>`${siteConfig.domain}/media/${encodeURIComponent(i.display_blob_key)}`),description:l.description,...(l.price_eur!==null?{offers:{"@type":"Offer",priceCurrency:'EUR',price:l.price_eur,availability:'https://schema.org/InStock',url:`${siteConfig.domain}/aggelies/${l.slug}`}}:{})};return <main className="page"><div className="container"><div className="detail-head"><div><h1>{l.title}</h1><span className="price">{formatPrice(l.price_eur)}</span></div><a className="call" href={`tel:${siteConfig.phoneE164}`}>☎ ΚΛΗΣΗ ΤΩΡΑ</a></div><div className="specbar"><div className="specbox"><small>ΤΙΜΗ ΠΩΛΗΣΗΣ</small><strong>{formatPrice(l.price_eur)}</strong></div><div className="specbox"><small>ΕΤΟΣ</small><strong>{l.registration_year}</strong></div><div className="specbox"><small>ΧΛΜ</small><strong>{formatKm(l.kilometers)}</strong></div><div className="specbox"><small>CC</small><strong>{formatCc(l.engine_cc)}</strong></div>{l.fuel&&<div className="specbox"><small>ΚΑΥΣΙΜΟ</small><strong>{l.fuel}</strong></div>}</div><MotorcycleGallery images={images} title={l.title}/><section className="content-card"><h2>Περιγραφή Αγγελίας</h2><p><strong>{siteConfig.sellerName}</strong> · <a href={`tel:${siteConfig.phoneE164}`}>{siteConfig.phoneDisplay}</a></p><div style={{whiteSpace:'pre-wrap'}}>{l.description}</div><div className="cta-row" style={{marginTop:20}}><a className="call" href={`tel:${siteConfig.phoneE164}`}>ΚΛΗΣΗ ΤΩΡΑ</a><a className="button" href={`viber://chat?number=${encodeURIComponent(siteConfig.viberNumber)}`}>Viber</a></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></div></main>}
